webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy.orm import relationship
from webapp.db import db
from webapp.main.models import Order


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, unique=True, primary_key=True)
    first_name = db.Column(db.String(500), nullable=True)
    middle_name = db.Column(db.String(1000), nullable=True)
    username = db.Column(db.String(1000), nullable=True)
    last_name = db.Column(db.String(1000), nullable=True)
    phone = db.Column(db.String(128), nullable=True)
    email = db.Column(db.String(1000), nullable=True)
    password = db.Column(db.String(1000), nullable=True)
    is_admin = db.Column(db.Boolean, nullable=True)

    orders = relationship("Order", back_populates="user")

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __repr__(self):
        return f"{self.first_name} {self.last_name}"

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length

class RegistrationForm(FlaskForm):
    first_name = StringField('Имя',validators=[DataRequired()])
    last_name = StringField ('Фамилия', validators=[DataRequired()])
    middle_name = StringField ('Отчество')
    username = StringField('Имя пользователя', validators=[DataRequired(), Length(min=5, max=20)])
    password = PasswordField('Пароль', validators=[DataRequired()])
    phone = StringField('Номер телефона', validators=[DataRequired()])
    email = StringField('Почта', validators=[DataRequired()])
    submit = SubmitField('Отправить', render_kw={"class": "btn btn-primary"})



class LoginForm(FlaskForm):
    email = StringField('Введите почту для входа', validators=[DataRequired()], render_kw={"class": "form-control"})
    password = PasswordField('Пароль', validators=[DataRequired()], render_kw={"class": "form-control"})
    submit = SubmitField('Войти', render_kw={"class": "btn btn-primary"})

 

webapp/user/views.py
from flask import Blueprint, flash, render_template, redirect, url_for
from flask_login import (
    login_user,
    logout_user,
    login_required,
    current_user,
)

from webapp.db import db
from webapp.user.models import User
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.main.models import Order

blueprint = Blueprint("user", __name__, url_prefix="/user")


@blueprint.route("/register")
def register():
    if current_user.is_authenticated:
        return redirect(url_for("user.user_page"))
    title = "Регистрация нового пользователя"
    registration_form = RegistrationForm()
    return render_template(
        "user/registration.html", page_title=title, form=registration_form
    )


@blueprint.route("/login")
def login():
    if current_user.is_authenticated:
        flash(f"Вы уже вошли, как пользователь: {current_user.username}")
        return redirect(url_for("user.user_page"))

    title = "Войдите в свой аккаунт"
    login_form = LoginForm()
    return render_template("user/login.html", page_title=title, form=login_form)


@blueprint.route("/process-login", methods=["POST"])
def process_login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter(User.email == form.email.data).first()
        if user and user.check_password(
            form.password.data
        ):  # поменять в будущем на метод проверки когда будет пароль+соль
            login_user(user)

            flash(f"{current_user.username}, Вы успешно вошли в свой аккаунт!")
            return redirect(
                url_for("user.user_page")
            )  # поменять потом на редирект на страницу пользователя
            # или админа(если пользователь админ)
    flash("Неправильный email или пароль")
    return redirect(url_for("user.login"))


@blueprint.route("/logout")
def logout():
    logout_user()
    flash("Вы вышли из аккаунта")
    return redirect(url_for("main.index"))


@blueprint.route("/user_page")
@login_required
def user_page():
    orders = (
        Order.query.filter_by(user_id=current_user.id).order_by(Order.id.desc()).all()
    )
    return render_template("user/user_page.html", orders=orders)


@blueprint.route("/process-registration", methods=["POST"])
def process_registration():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            email=form.email.data,
            is_admin=False,
        )
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("Вы успешно зарегистрировались!")
        return redirect(url_for("user.login"))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f"Поле {getattr(form, field).label.text} - {error}", "danger")

webapp/templates/user/login.html
<link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<section class="bg-light py-3 py-md-5">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5 col-xxl-4">
          <div class="card border border-light-subtle rounded-3 shadow-sm">
            <div class="card-body p-3 p-md-4 p-xl-5">
              <div class="text-center mb-3">
                <a href="Login">
                </a>
              </div>
              <h2 class="fs-6 fw-normal text-center text-secondary mb-4">{{ page_title }}</h2>
              {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                  {% for message in messages %}
                      {{ message }}<br>
                  {% endfor %}
                </div>
                    {% endif %}
              {% endwith %}
              <form action="{{ url_for('user.process_login') }}" method="POST">
                {{ form.hidden_tag() }}
                <div class="row gy-2 overflow-hidden">
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      {{ form.email.label }}
                      {{ form.email(class="form-control", onfocus="this.previousElementSibling.style.display='none';", 
                      onblur="if(this.value === '') this.previousElementSibling.style.display='block';") }}
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      {{ form.password.label }}
                      {{ form.password(class="form-control", onfocus="this.previousElementSibling.style.display='none';", 
                      onblur="if(this.value === '') this.previousElementSibling.style.display='block';") }}
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="d-flex gap-2 justify-content-between">
                      <a href="/forgot_password" class="link-primary text-decoration-none">Забыли пароль?</a>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="d-grid my-3">
                      {{ form.submit() }}
                    </div>
                  </div>
                  <div class="col-12">
                    <p class="m-0 text-secondary text-center">Нет аккаунта? <a href="/register" class="link-primary text-decoration-none">Зарегистироваться!</a></p>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

webapp/templates/user/registration.html
<link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<section class="bg-light py-3 py-md-5">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5 col-xxl-4">
          <div class="card border border-light-subtle rounded-3 shadow-sm">
            <div class="card-body p-3 p-md-4 p-xl-5">
              <div class="text-center mb-3">
                <a href="Login">
                </a>
              </div>
              <h2 class="fs-6 fw-normal text-center text-secondary mb-4">{{ page_title }}</h2>
              <form action="{{ url_for('user.process_registration') }}" method="POST">
                {{ form.hidden_tag() }}
                <div class="row gy-2 overflow-hidden">
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      {{ form.first_name.label }}
                      {{ form.first_name(class="form-control", onfocus="this.previousElementSibling.style.display='none';", 
                      onblur="if(this.value === '') this.previousElementSibling.style.display='block';") }}
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      {{ form.last_name.label }}
                      {{ form.last_name(class="form-control", onfocus="this.previousElementSibling.style.display='none';", 
                      onblur="if(this.value === '') this.previousElementSibling.style.display='block';") }}
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      {{ form.middle_name.label }}
                      {{ form.middle_name(class="form-control", onfocus="this.previousElementSibling.style.display='none';", 
                      onblur="if(this.value === '') this.previousElementSibling.style.display='block';") }}
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      {{ form.username.label }}
                      {{ form.username(class="form-control", onfocus="this.previousElementSibling.style.display='none';", 
                      onblur="if(this.value === '') this.previousElementSibling.style.display='block';") }}
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      {{ form.password.label }}
                      {{ form.password(class="form-control", onfocus="this.previousElementSibling.style.display='none';", 
                      onblur="if(this.value === '') this.previousElementSibling.style.display='block';") }}
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      {{ form.phone.label }}
                      {{ form.phone(class="form-control", onfocus="this.previousElementSibling.style.display='none';", 
                      onblur="if(this.value === '') this.previousElementSibling.style.display='block';") }}
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      {{ form.email.label }}
                      {{ form.email(class="form-control", onfocus="this.previousElementSibling.style.display='none';", 
                      onblur="if(this.value === '') this.previousElementSibling.style.display='block';") }}
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="d-grid my-3">
                      {{ form.submit() }}
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

webapp/templates/user/user_page.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="text-center mb-4">
        <h1>Личный кабинет</h1>
    </div>

    <div class="card">
        <h2 class="card-header">Купленные билеты</h2>
        <div class="scroll-container">
            <ul class="list-group">
            {% for order in orders %}
                <li class="list-group-item"> {{ order.showtime.movie.title }} | Дата: {{ order.showtime.date }} | Время: {{ order.showtime.time.strftime('%H:%M') }} | {% if order.seats[0]['row'] == 'VIP-hall' %} VIP-зал {% else %} {% for seat in order.seats %} Ряд: {{ seat.row }} - Место: {{ seat.seat }}; {% endfor %} {% endif %}</li>
            {% endfor %}
            </ul>
        </div>
    </div>
    
    <div class="card mt-4">
        <div class="card-header">
            **Редактировать профиль**
        </div>
        <div class="card-body">
            <form>
                <div class="form-group">
                    <label for="email">Электронная почта</label>
                    <input type="email" class="form-control" id="email" placeholder="Введите новый email">
                </div>
                <div class="form-group">
                    <label for="phone">Телефон</label>
                    <input type="tel" class="form-control" id="phone" placeholder="Введите новый телефон">
                </div>
                <button type="submit" class="btn btn-primary">Сохранить изменения</button>
            </form>
            <div>
                <a href="/logout" class="link-primary text-decoration-none">Выйти из личного кабинета.</a>
            </div>
        </div>
    </div>
</div>

{% endblock  %}