webapp/main/models.py
from sqlalchemy.orm import relationship

from webapp.db import db



class Movie(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    age_rating = db.Column(db.String(10), nullable=False)
    year = db.Column(db.Integer, nullable=False)
    duration = db.Column(db.Integer, nullable=False)
    description = db.Column(db.Text, nullable=False)
    genre = db.Column(db.String(50), nullable=False)
    counry = db.Column(db.String(50), nullable=False)
    img_url = db.Column(db.String(250), nullable=False)

    showtimes = relationship("Showtime", back_populates="movie")

    def __repr__(self):
        return f"<Movie {self.title}>"


class Showtime(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    movie_id = db.Column(db.Integer, db.ForeignKey("movie.id"), nullable=False)
    hall_id = db.Column(db.Integer, db.ForeignKey("hall.id"), nullable  =False)
    date = db.Column(db.Date, nullable=False)
    time = db.Column(db.Time, nullable=False)
    seats = db.Column(db.JSON, nullable=False)
    price = db.Column(db.Numeric(10, 2), nullable=False)

    hall = relationship("Hall", back_populates="showtimes")
    movie = relationship("Movie", back_populates="showtimes")
    orders = db.relationship('Order', back_populates='showtime')

    def __repr__(self):
        return f"<Showtime: {self.date}> {self.time} - {self.movie}"

class Hall(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    hall_name = db.Column(db.String(100), nullable=False)

    seats = relationship("Seats", back_populates="hall")
    showtimes = relationship("Showtime", back_populates="hall")

    def __repr__(self):
        return f"<Hall: {self.hall_name}>"


class Seats(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    hall_id = db.Column(db.Integer, db.ForeignKey("hall.id"), nullable=False)
    row = db.Column(db.Integer, nullable=False)
    seats = db.Column(db.JSON, nullable=False)
    coefficient_price = db.Column(db.REAL, nullable=False)

    hall = relationship("Hall", back_populates="seats")

    def __repr__(self):
        return f"<Seats: {self.hall_id}>"
    
class OrderStatus(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    status_name = db.Column(db.String(100), nullable=False)

    orders = relationship("Order", back_populates="status")

    def __repr__(self):
        return f"<OrderStatus: {self.name}>"


class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    showtime_id = db.Column(db.Integer, db.ForeignKey("showtime.id"), nullable=False)
    status_id = db.Column(db.Integer, db.ForeignKey("order_status.id"), nullable=False)
    payment_type = db.Column(db.String(100), nullable=False, default="Online")
    seats = db.Column(db.JSON)
    datetime = db.Column(db.DateTime, default=db.func.now())

    user = relationship("User", back_populates="orders")
    tickets = relationship("Ticket", back_populates="order")
    showtime = relationship("Showtime", back_populates="orders")
    status = relationship("OrderStatus", back_populates="orders")

    def __repr__(self):
        return f"<Order: {self.user_id}>"


class Ticket(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    order_id = db.Column(db.Integer, db.ForeignKey("order.id"), nullable=False)
    row = db.Column(db.Integer, nullable=False)
    number = db.Column(db.Integer, nullable=False)

    order = relationship("Order", back_populates="tickets")

    def __repr__(self):
        return f"<Ticket: {self.order_id}>"

webapp/main/views.py
from datetime import date, datetime
from decimal import Decimal
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify, session
from flask_login import current_user, login_required
from sqlalchemy.orm import joinedload
from sqlalchemy.orm.attributes import flag_modified
from sqlalchemy.sql import func
from webapp.db import db
from webapp.libs.chek_card import validate_card_expiry, validate_card_number, validate_cvv
from .models import Movie, Showtime, Order, Seats

import json


blueprint = Blueprint("main", __name__)


@blueprint.route("/")
def index():
    random_movies = (
        Movie.query.options(joinedload(Movie.showtimes))
        .order_by(func.random())
        .limit(3)
        .all()
    )
    showtimes = Showtime.query.limit(6).all()
    # session_data = dict(session)
    # print(session_data)
    return render_template("main/index.html", movies=random_movies, showtimes=showtimes)


@blueprint.route("/showtime/<int:showtime_id>")
def showtime_detail(showtime_id):
    showtime = Showtime.query.options(joinedload(Showtime.movie)).get_or_404(
        showtime_id
    )
    return render_template(
        "main/theatre-area.html", showtime=showtime, current_user=current_user
    )


@blueprint.route("/order/<int:order_id>")
def order(order_id):
    order = Order.query.get_or_404(order_id)
    showtime = Showtime.query.get(order.showtime_id)
    if order.seats[0]['row'] == 'VIP-hall':
        return render_template("main/order.html", order=order, price=round(float(order.showtime.price), 2))
    total_price = Decimal(0)
    for seat in order.seats:
        seats = Seats.query.filter_by(hall_id=showtime.hall_id, row=seat['row']).first()
        total_price += Decimal(seats.coefficient_price) * showtime.price
    order.total_price = total_price    
    db.session.commit()
    return render_template("main/order.html", order=order, price=round(float(total_price), 2))

@blueprint.route("/submit-seats", methods=["POST"])
def submit_seats():
    if not current_user.is_authenticated:
        flash('Для оформления заказа необходимо авторизоваться!', 'warning')
        return redirect(url_for("user.login"))
    selected_seats = request.form.get("selectedSeats")
    selected_seats_list = json.loads(selected_seats)
    if len(selected_seats_list) > 0:
        showtime_id = request.form.get("showtime_id")
        order = Order(user_id=current_user.id, showtime_id=showtime_id, status_id=2, seats=selected_seats_list, datetime=datetime.now())
        showtime = Showtime.query.get(showtime_id)
        
        for seat in selected_seats_list:
            showtime.seats[int(seat["row"]) - 1][int(seat["seat"]) - 1] = True
        flag_modified(showtime, "seats")
        db.session.add(order)
        db.session.add(showtime)
        db.session.commit()
        
        return redirect(url_for("main.order", order_id=order.id))
    else:
        flash('Для заказа билета выберите места!', 'warning')
        return redirect(url_for("main.index"))
    

@blueprint.route('/check-card', methods=['POST'])
def check_card():
    card_number = request.form.get('cardNumber')
    card_expiry = request.form.get('cardExpiry')
    card_cvv = request.form.get('cardCVV')
    order_id = request.form.get('order_id')
    order = Order.query.get(order_id)
        
    if not validate_card_number(card_number):
        flash('Неверный номер карты!', 'warning')
        return redirect(url_for("main.order", order_id=order.id)) 

    if not validate_card_expiry(card_expiry):
        flash('Неверный срок действия карты!', 'warning')
        return redirect(url_for("main.order", order_id=order.id)) 

    if not validate_cvv(card_cvv):
        flash('Неверный CVV', 'warning')
        return redirect(url_for("main.order", order_id=order.id))

    # Здесь должна быть логика проверки данных карты через платежный шлюз

    order = Order.query.get(order_id)
    order.status_id = 3
    db.session.commit()
    
    flash('Заказ оплачен!', 'success')
    return redirect(url_for("user.user_page"))

@blueprint.route("/book_vip")
def book_vip():
    movies = Movie.query.order_by(Movie.id.desc()).limit(5).all()
    return render_template("main/book_vip.html", movies=movies)

@blueprint.route("/submit_vip", methods=["POST"])
def submit_vip():
    if not current_user.is_authenticated:
        flash('Для оформления заказа необходимо авторизоваться!', 'warning')
        return redirect(url_for("user.login"))
    movie_id = request.form.get("movieSelect")
    datetime_show = request.form.get("datePicker").split("T")
    if not movie_id:
        flash('Для оформления заказа необходимо выбрать сеанс !', 'warning')
        return redirect(url_for("main.book_vip"))        
    if not datetime_show:
        flash('Для оформления заказа необходимо выбрать дату и время !', 'warning')
        return redirect(url_for("main.book_vip")) 
    date_show = datetime.strptime(datetime_show[0], '%Y-%m-%d')
    time_show = datetime.strptime(datetime_show[1], '%H:%M')
    date_now = datetime.now()
    if date_show < date_now:
        flash('Для оформления заказа необходимо выбрать дату позднее сегодняшнего дня !', 'warning')
        return redirect(url_for("main.book_vip"))
    showtime = Showtime(movie_id=movie_id, date=date_show, time=time_show, hall_id=2, seats=[[True]], price=10000)
    db.session.add(showtime)
    db.session.commit()
    order = Order(user_id=current_user.id, showtime_id=showtime.id, status_id=2, seats=[{"row": 'VIP-hall', "seat": showtime.movie.title}], datetime=datetime.now())
    db.session.add(order)
    db.session.commit()
    return redirect(url_for("main.order", order_id=order.id))

webapp/templates/main/book_vip.html
{% extends "base.html" %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 text-center">
        
            <h1>Бронирование VIP-зала</h1>
        
            <form action="/submit_vip" method='POST'>
                <div class="form-group">
                    <label for="datePicker">Выберите дату:</label>
                    <input type="datetime-local" class="form-control" name="datePicker" id="datePicker" placeholder="Выберите дату">
                </div>
                <div class="form-group">
                    <label for="movieSelect">Выберите фильм:</label>
                    <select class="form-control" name="movieSelect" id="movieSelect">
                        {% for movie in movies %}
                            <option value="{{ movie.id }}">{{ movie.title }}</option>                
                        {% endfor %}
                    </select>
                </div>
                
                <button type="submit" class="btn btn-primary">Забронировать</button>
            </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js">/* Скрипт выбора даты для бутстрап 1.9 */</script> 
<!-- <script>
    $(document).ready(function(){
        $('#datePicker').datepicker({
            format: 'dd.mm.yyyy',
            language: 'ru',
            autoclose: true
        });
    });
</script> -->

{% endblock %}

webapp/templates/main/index.html
{% extends "base.html" %}

{% block content %}

<div class="hero text-center">
    <h1>Добро пожаловать в LearnPython-Cinema!</h1>
</div>

<section class="container my-5">
    <h2 class="text-center">Популярные в прокате фильмы</h2>
    <div class="row">
        {% for movie in movies %}
            <div class="col-md-4">
                <div class="card mb-4" style="height: 100%;">
                    <img src={{ movie.img_url }} class="card-img-top" alt={{ movie.title }}>
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">{{ movie.title }}</h5>
                        <p class="card-text">Жанр: {{ movie.genre }}<br>Длительность: {{ movie.duration }} мин<br>Страна: {{ movie.counry }}</p>
                        <a href="{{ url_for('main.showtime_detail', showtime_id=movie.showtimes[0].id) }}" class="btn btn-primary mt-auto w-50">
                            Купить билет
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
        
    </div>
</section>

<!-- Расписание -->
<article id="part1" ></article>
<section class="container my-5">
    <h2 class="text-center">Расписание сеансов</h2>
    <div class="row">
        {% for showtime in showtimes %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">{{ showtime.movie.title }}</h4>
                        <p class="card-text">{{ showtime.time.strftime('%H:%M') }} | Зал {{ showtime.hall_id }}</p>
                        <a href="{{ url_for('main.showtime_detail', showtime_id=showtime.id) }}" class="btn btn-primary mt-auto w-50">
                            Купить билет
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
</section>

<footer class="bg-dark text-white text-center p-3">
    <div class="container">
        <p>© С любовью группа Максима Мокрых</p>
        <article id="part2" ></article>
        <p> Контакты: г. Москва, ул.Кино, д.1 </p>
        <nav>
            <a class="text-white" href="/">LearnPython-Cinema</a>
        </nav>
    </div>
</footer>

{% endblock  %}

webapp/templates/main/order.html
{% extends "base.html" %}

{% block content %}

        <!-- Форма оплаты -->
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 text-center">
            <h2>Оплата</h2>
            <div class="form-group">
                <label for="selectedSeats">Выбранные места:</label>
                {% if order.seats[0]['row'] == 'VIP-hall' %}
                    <textarea class="form-control" id="selectedSeats" rows="3" readonly> {{ order.seats[0]['row'] }} - Фильм: {{ order.seats[0]['seat'] }};</textarea>
                {% else %}
                    <textarea class="form-control" id="selectedSeats" rows="3" readonly>{% for seat in order.seats %} Ряд: {{ seat.row }} - Место: {{ seat.seat }}; {% endfor %}</textarea>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="cardNumber">Стоимость билетов:</label>
                <input type="text" class="form-control" id="price" placeholder={{ price }} readonly>
            </div>
            <form action="/check-card" method="POST">
                <input type="hidden" name="order_id" value="{{ order.id }}">
                <div class="form-group">
                    <label for="cardNumber">Номер карты:</label>
                    <input type="text" class="form-control" id="cardNumber" name="cardNumber" placeholder="Номер карты">
                </div>
                <div class="form-group">
                    <label for="cardExpiry">Срок действия:</label>
                    <input type="text" class="form-control" id="cardExpiry" name="cardExpiry" placeholder="ММ/ГГ">
                </div>
                <div class="form-group">
                    <label for="cardCVV">CVV:</label>
                    <input type="text" class="form-control" id="cardCVV" name="cardCVV" placeholder="CVV">
                </div>
                <img src="/static/images/card.jpeg" class="card-img mb-3" alt="Банковская карта">
                <button type="submit" class="btn btn-primary btn-block">Оплатить</button>
            </form>
        </div>
    </div>
</div>        


{% endblock  %}

webapp/templates/main/theatre-area.html
{% extends "base.html" %}

{% block content %}

    <div class="container-fluid my-4 d-flex">
        <div class="seating-chart flex-grow-1">
            <h2 class="text-center">Зрительный зал №1</h2>
            <h2 class="text-center"> {{ showtime.movie.title }}</h2>
            <h2 class="text-center"> {{ showtime.date}} - {{ showtime.time.strftime('%H:%M') }}</h2> 
            {% for i in range(showtime.seats|length) %}
                <div class="row" data-row="{{ i + 1 }}">
                    <span class="row-label">{{ i + 1 }}</span>
                    {% for seat in showtime.seats[i] %}
                        <div class="seat {% if seat %}taken{% endif %}">
                            <span class="seat-label {% if seat %}taken{% endif %}">{{ loop.index0 + 1 }}</span>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}


            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
            <script>
                $(document).ready(function() {
                    var selectedSeats = [];
                    
                    function updateSeatInfo(seat) {
                        var row = seat.closest('.row').data('row');
                        var seatNumber = seat.find('.seat-label').text();
                        
                        if (seat.hasClass('selected')) {
                            selectedSeats.push({ row: row, seat: seatNumber });
                        } else {
                            selectedSeats = selectedSeats.filter(function(s) {
                                return !(s.row === row && s.seat === seatNumber);
                            });
                        }
                        
                        // Обновляем отображение всех выбранных мест
                        updateSelectedSeatsDisplay();
                    }
                    
                    function updateSelectedSeatsDisplay() {
                        var seatInfoHtml = '<h3>Выбранные места:</h3>';
                        if (selectedSeats.length === 0) {
                            seatInfoHtml += '<p>Места не выбраны</p>';
                        } else {
                            seatInfoHtml += '<ul class="no-markers">';
                            selectedSeats.forEach(function(seat) {
                                seatInfoHtml += '<li>Ряд ' + seat.row + ', Место ' + seat.seat + '</li>';
                            });
                            seatInfoHtml += '</ul>';
                        }
                        $('#seat-info').html(seatInfoHtml);
                    }

                    // Обработка клика по месту
                    $('.seat').on('click', function() {
                        if (!$(this).hasClass('taken')) {
                            $(this).toggleClass('selected');
                            updateSelectedSeats();
                        }
                        updateSeatInfo($(this));
                    });

                    $('.seat-label').on('click', function() {
                        if (!$(this).hasClass('taken')) {
                            $(this).toggleClass('selected');
                        }
                    });

        
                    // Обновление информации о выбранных местах
                    function updateSelectedSeats() {
                        var selectedSeats = $('.seat.selected').length;
                        $('#selected-count').text(selectedSeats);
                    }
                    $('.btn-primary').click(function() {
                        $('#selectedSeats').val(JSON.stringify(selectedSeats)); // Преобразуем массив в строку JSON
                    });
                });
            </script>
           
        
        <!-- Переход к форме оплаты -->
        <div class="container d-flex align-items-center justify-content-center" style="min-height: 20vh;">
            <div class="row">
                <div class="col-12 text-center">
                    <div id="seat-info" class="mb-3"></div>
                    <div class="mb-3">Выбрано мест: <span id="selected-count">0</span></div>
                    <form action="/submit-seats" method="POST">
                        <input type="hidden" name="selectedSeats" id="selectedSeats" value="">
                        <input type="hidden" name="showtime_id" value="{{ showtime.id }}"> 
                        <button type="submit" class="btn btn-primary btn-block">Купить билет</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock  %}